### ISSUE TITLE
Wrong license?

### ISSUE THREAD

**Issue by oblitum** [jacobtomlinson/carte-noire-hugo#1]
README states it's GPLv3 but license file in repo is MIT. Just pointing, I have no preference, both are fine for me.

**Comment by jacobtomlinson** [comment]
Good spot thanks. This project is GPLv3 as the README states. I've corrected the LICENSE file.

**Comment by oblitum** [comment]
Nice. I've recently changed my blog's theme to this one, it's great, many thanks for it.

- [Site](http://nosubstance.me/)
- [Changes](https://gitlab.com/oblitum/carte-noire/commit/8c423a8da149f6b146f3ef391943dbfee9aa0553) (I've added KaTeX [[heavy example](http://nosubstance.me/post/nature-invented-it-first/)] and upgraded Font Awesome to 5.9)

I have a post on [hosting Hugo on GitLab Pages](http://nosubstance.me/post/a-great-toolset-for-static-blogging/), it has native support, like Jekyll on GitHub, I find it quite convenient and [simple to setup](https://gitlab.com/oblitum/nosubstance.me/blob/master/.gitlab-ci.yml).

**Comment by jacobtomlinson** [comment]
> Changes

Do you have any interest in making a PR with these changes. Would be super helpful.

> I have a post on hosting Hugo on GitLab Pages

That's awesome I didn't know they did that.
